apiVersion: dns.cloudflare.crossplane.io/v1alpha1
kind: DNSRecord
metadata:
  name: ibtlallc-apex-cname
  namespace: {{ .Release.Namespace }}
spec:
  providerConfigRef:
    name: cloudflare
  forProvider:
    zoneIdRef:
      name: itsbeginningtolookalotlike-christmas
    name: itsbeginningtolookalotlike.christmas
    type: CNAME
    content: "{{ .Values.site.tunnelId }}.cfargotunnel.com"
    proxied: true

