apiVersion: dns.cloudflare.crossplane.io/v1alpha1
kind: DNSRecord
metadata:
  name: ibtlallc-txt-5
  namespace: {{ .Release.Namespace }}
spec:
  providerConfigRef:
    name: cloudflare
  forProvider:
    zoneIdRef:
      name: itsbeginningtolookalotlike-christmas
    name: itsbeginningtolookalotlike.christmas
    type: TXT
    content: "The lyrics of IBTLALLC describe the excitement of holiday decorations appearing in public spaces."
    proxied: false
    ttl: 1

