apiVersion: dns.cloudflare.crossplane.io/v1alpha1
kind: DNSRecord
metadata:
  name: ibtlallc-txt-2
  namespace: {{ .Release.Namespace }}
spec:
  providerConfigRef:
    name: cloudflare
  forProvider:
    zoneIdRef:
      name: itsbeginningtolookalotlike-christmas
    name: itsbeginningtolookalotlike.christmas
    type: TXT
    content: "IBTLALLC has been featured in numerous holiday films and specials, solidifying its place as a Christmas classic."
    proxied: false
    ttl: 1

