apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: {{ .Values.site.cloudflared.replicaCount }}
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: cloudflared
          image: {{ .Values.site.cloudflared.image.repository }}:{{ .Values.site.cloudflared.image.tag }}
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-tunnel-token
                  key: token
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 10
