apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
spec:
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: cloudflare-tunnel-token
  data:
    - secretKey: token
      remoteRef:
        key: itsbeginningtolookalotlikechristmas/cloudflare-tunnel
        property: token
